### ISSUE TITLE
TestngMetrics: java.lang.ClassCastException: java.lang.reflect.Method cannot be cast to java.lang.CharSequence

### ISSUE THREAD

**Issue by adiralashiva8** [adiralashiva8/testng-metrics#14]
```
[TestNG] Reporter com.github.testng.MetricsListener@5056dfcb failed
java.lang.ClassCastException: java.lang.reflect.Method cannot be cast to java.lang.CharSequence
    at java.lang.String.join(String.java:2503)
    at com.github.internal.HtmlBuilder.gatherTestInformation(HtmlBuilder.java:480)
    at com.github.internal.HtmlBuilder.buildMethodMetricsTab(HtmlBuilder.java:199)
    at com.github.testng.MetricsListener.generateReport(MetricsListener.java:40)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at com.github.testng.MetricsListener.generateReport(MetricsListener.java:24)
    at org.testng.TestNG.generateReports(TestNG.java:1184)
    at org.testng.TestNG.run(TestNG.java:1109)
    at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
    at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
    at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
    at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by adiralashiva8** [comment]
Solution: Should not check for data provider parameters in methodMetricsTab

**Comment by adiralashiva8** [comment]
Fixed in this https://github.com/adiralashiva8/testng-metrics/commit/3af58ac06776e3d9f8bfb35538cba544fe9114b5 commit
